services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - wp_files:/var/www/inception
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - inception_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_files:/var/www/inception:ro
    restart: on-failure
    networks:
      - inception_net

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yaharkat/data/mariadb
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yaharkat/data/wordpress

networks:
  inception_net:
    driver: bridge
    
